### ISSUE TITLE
Add replace-colorthemes to a package repository

### ISSUE THREAD

**Issue by rubic** [emacs-jp/replace-colorthemes#10]
Add replace-colorthemes to one of the 3rd-party package repositories:

 * https://marmalade-repo.org/
 * MELPA

**Comment by mmckinst** [comment]
it is now in MELPA under color-theme-modern. see https://github.com/milkypostman/melpa/pull/3282

**Comment by syohex** [comment]
@mmckinst Thanks for your work :+1:
