### ISSUE TITLE
Dark cursor in blue-mood (and others)

### ISSUE THREAD

**Issue by vedvyas** [emacs-jp/replace-colorthemes#17]
When using the blue-mood theme in Emacs 24.5, the cursor is some dark color instead of DarkGoldenrod1. Changing the cursor face color from `:foreground` to `:background` fixes it. Found out that this is explained in the cursor face description:

> Basic face for the cursor color under X. Hide
   Currently, only the `:background' attribute is meaningful; all
   other attributes are ignored.  The cursor foreground color is
   taken from the background color of the underlying text.

**Comment by syohex** [comment]
Oh, I mistook cursor color configuration. Thanks for reporting issue.

**Comment by syohex** [comment]
I have applied #20. Please check latest version.

**Comment by vedvyas** [comment]
Thank you! I installed color-theme-modern-20160410.2137 from Melpa. It reflects your recent changes and works beautifully :+1:
