### ISSUE TITLE
Mode-line settings didn't work

### ISSUE THREAD

**Issue by dgentry** [emacs-jp/replace-colorthemes#30]
First, thank you for this package.  It motivated me to switch over from my old color-themes, which took a while to load.

I'm using emacs 26.3 which comes with Mac OS Mojave.

The ported themes I downloaded all used `(modeline. . . ` instead of `(mode-line. . .`.  This made the mode-line parts of the themes not work for me.  Once I changed `modeline` to `mode-line everywhere, the mode lines worked as I expected.

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #31. Please check latest version.
