### ISSUE TITLE
Port of gruber-darker-theme

### ISSUE THREAD

**Issue by vdobler** [emacs-jp/replace-colorthemes#32]
Could you port gruber-darker (see e.g. http://github.com/rexim/gruber-darker-theme)?
It is IMHO the most calm and clear dark theme.
Thanks in advance!

**Comment by syohex** [comment]
It is not necessary to port. Because it is implemented by emacs color theme scheme. The purpose of this repository is porting from older color themes to emacs color theme scheme.

Moreover it is already registered in melpa(https://melpa.org/#/gruber-darker-theme).
