### ISSUE TITLE
No italic in calm-forest on org-mode

### ISSUE THREAD

**Issue by thomasluquet** [emacs-jp/replace-colorthemes#9]
Hi, on org-mode, when i do a /stuff/ with calm-forest, it does not display an italic texte. (Or underline)
Am i the only one ?
(Sorry for my engish)

**Comment by takaxp** [comment]
I believe org mode has integrated many changes from 2014 until today. So we can just close this issue if we (including @thomasluquet) do not have strong objections.

**Comment by takaxp** [comment]
I would like to close this issue if no reactions we will receive by 2019-10-17.
